### ISSUE TITLE
About Checkpoints

### ISSUE THREAD

**Issue by haohaodw** [Yufang-Liu/clip_hallucination#1]
Very interesting work. 
I noticed that you published the checkpoint, and there is a subfolder called CLIP under the huggingface link. Does this CLIP refer to the full fine-tuning CLIP mentioned in your paper, or is it the original CLIP?

**Comment by Yufang-Liu** [comment]
> Very interesting work. I noticed that you published the checkpoint, and there is a subfolder called CLIP under the huggingface link. Does this CLIP refer to the full fine-tuning CLIP mentioned in your paper, or is it the original CLIP?

It is the fine-tuned model.

**Comment by haohaodw** [comment]
Thanks for your reply.
